### PR TITLE
Routing algorithm overhaul

### LINKED ISSUE #389: Routing algorithm is broken when using 3+ level nested zones
Hi there, 

# Context
> # tl; dr : clarifying my use case
> I need to represent a complex hyerarchical network with far more than 2 nested zones via the C API.

For my PhD thesis I'm working in a Fog architecture simulation using Batsim.
My platform contains machines composed of multiple GPU/CPU, which means each machine is a StarZone with hosts. 
## Overview of my platform :
sgp_het_fog

As my platform is heavy heterogeneous and has many levels of Zones, I think my work can contribute, some ways, to this fantastic library.

# Routing issue
It seems that the routing algorithm does not work for many recursive subzones ( more than 3 included ).
I made a simple scenario example where this problem occurs, using [this flatify program](https://gist.github.com/JRodez/e5f3b22fdecaa9285c1fb905e479b330) over 
[a 3 level platform](https://gist.github.com/JRodez/2a4645edb045481557af0facb4e38ecb#file-routing_cluster_bug-cpp):

Overview of the log [clusterbugged.log](https://github.com/simgrid/simgrid/files/13719487/clusterbugged.log) :

> ```
> [0.000000] ./src/xbt/exception.cpp:48: [xbt_exception/CRITICAL] Uncaught exception std::out_of_range: unordered_map::at
> [0.000000] ./src/xbt/exception.cpp:75: [xbt_exception/CRITICAL] Current backtrace:
>   ->  #0 0x00007F3558AEFBC7 in /lib/simgrid_lib/lib64/libsimgrid.so.3.35.1
>   ->  #1 0x00007F35586B4F8A in /nix/store/myw67gkgayf3s2mniij7zwd79lxy8v0k-gcc-12.3.0-lib/lib/libstdc++.so.6
>   ->  #2 0x00007F35586B4FF5 in /nix/store/myw67gkgayf3s2mniij7zwd79lxy8v0k-gcc-12.3.0-lib/lib/libstdc++.so.6
>   ->  #3 0x00007F35586B5247 in /nix/store/myw67gkgayf3s2mniij7zwd79lxy8v0k-gcc-12.3.0-lib/lib/libstdc++.so.6
>   ->  #4 std::__throw_out_of_range(char const*) in /nix/store/myw67gkgayf3s2mniij7zwd79lxy8v0k-gcc-12.3.0-lib/lib/libstdc++.so.6
>   ->  #5 simgrid::kernel::routing::StarZone::get_local_route(simgrid::kernel::routing::NetPoint const*, simgrid::kernel::routing::NetPoint const*, simgrid::kernel::routing::Route*, double*) in /lib/simgrid_lib/lib64/libsimgrid.so.3.35.1
>   ->  #6 simgrid::kernel::routing::NetZoneImpl::get_global_route_with_netzones(simgrid::kernel::routing::NetPoint const*, simgrid::kernel::routing::NetPoint const*, std::vector<simgrid::kernel::resource::StandardLinkImpl*, std::allocator<simgrid::kernel::resource::StandardLinkImpl*> >&, double*, std::unordered_set<simgrid::kernel::routing::NetZoneImpl*, std::hash<simgrid::kernel::routing::NetZoneImpl*>, std::equal_to<simgrid::kernel::routing::NetZoneImpl*>, std::allocator<simgrid::kernel::routing::NetZoneImpl*> >&) in /lib/simgrid_lib/lib64/libsimgrid.so.3.35.1
>   ->  #7 simgrid::kernel::routing::NetZoneImpl::get_global_route_with_netzones(simgrid::kernel::routing::NetPoint const*, simgrid::kernel::routing::NetPoint const*, std::vector<simgrid::kernel::resource::StandardLinkImpl*, std::allocator<simgrid::kernel::resource::StandardLinkImpl*> >&, double*, std::unordered_set<simgrid::kernel::routing::NetZoneImpl*, std::hash<simgrid::kernel::routing::NetZoneImpl*>, std::equal_to<simgrid::kernel::routing::NetZoneImpl*>, std::allocator<simgrid::kernel::routing::NetZoneImpl*> >&) in /lib/simgrid_lib/lib64/libsimgrid.so.3.35.1
>   ->  #8 simgrid::kernel::routing::NetZoneImpl::get_global_route(simgrid::kernel::routing::NetPoint const*, simgrid::kernel::routing::NetPoint const*, std::vector<simgrid::kernel::resource::StandardLinkImpl*, std::allocator<simgrid::kernel::resource::StandardLinkImpl*> >&, double*) in /lib/simgrid_lib/lib64/libsimgrid.so.3.35.1
>   ->  #9 simgrid::s4u::Engine::flatify_platform[abi:cxx11]() const in /lib/simgrid_lib/lib64/libsimgrid.so.3.35.1
>   ->  #10 0x00000000004025F6 in /home/user/work/sgnetdump_src//builddir/sgnetdumpflatify
>   ->  #11 0x00007F355843BFCE in /nix/store/qn3ggz5sf3hkjs2c797xf7nan3amdxmp-glibc-2.38-27/lib/libc.so.6
>   ->  #12 __libc_start_main in /nix/store/qn3ggz5sf3hkjs2c797xf7nan3amdxmp-glibc-2.38-27/lib/libc.so.6
>   ->  #13 0x00000000004021F5 in /home/user/work/sgnetdump_src//builddir/sgnetdumpflatify
> ```

By inspecting the source code of SG, I understand that in [NetZoneImpl::get_global_route_with_netzones](https://github.com/simgrid/simgrid/blob/5528353ea04b03763457e4806b24ea0d8c1d7197/src/kernel/routing/NetZoneImpl.cpp#L574) we make the assumption that if `src_ancestor == dst_ancestor`, so we don't have to elaborate further for finding route parts.

For each route part, we ask to the corresponding zone (StarZone.cpp) what is the route between src and dst. 
The problem is that if src is in a subzone, the zone we ask is not responsible for this src, so id will be interpreted as id of another object of the zone. If the src id is not known, it just crashes as above.

What would be a proper workaround  ?

### PR DESCRIPTION
**Pull request by JRodez**
Clean rebase of #392 which fixes #389.
Maybe it would be nice having more tests. 
Also we can add a fix to #400 in this MR if needed.

Have a nice day.
JR

### CODE REVIEW

**Comment by JRodez** [comment]
Note that I have removed the macros defined in [d4630dc](https://github.com/simgrid/simgrid/pull/401/commits/d4630dc6bfa111ccf2fce573fe7a11b50f1449aa) to definitively replace the base algorithm.

File: src/kernel/routing/NetZoneImpl.cpp [hunk 1]
```diff
@@ -575,58 +466,192 @@ void NetZoneImpl::get_global_route(const NetPoint* src, const NetPoint* dst,
...
+    *common_ancestor = parent;
+  }
+
+  // maybe we should remove this check for performance reasons
+  xbt_enforce(parent != nullptr, "No common ancestor found for '%s' and '%s'", src->get_cname(), dst->get_cname());
+  xbt_enforce(*src_ancestor != nullptr, "No src ancestor found for '%s' and '%s'", src->get_cname(), dst->get_cname());
+  xbt_enforce(*dst_ancestor != nullptr, "No dst ancestor found for '%s' and '%s'", src->get_cname(), dst->get_cname());
+}
+
+/* Compute the route between a leaf NetPoint and an upper router */
```
Comment (frs69wq) [inline src/kernel/routing/NetZoneImpl.cpp:539]: I have a hard time visualizing where in the hierarchy is that function used. Maybe an illustration or a more detailed comment would help.

File: src/kernel/routing/NetZoneImpl.cpp [hunk 2]
```diff
@@ -692,8 +717,10 @@ void NetZoneImpl::set_gateway(const std::string& name, NetPoint* router)
 
 NetPoint* NetZoneImpl::get_gateway() const
 {
-  xbt_enforce(not gateways_.empty(), "No default gateway has been defined for NetZone '%s'. Try to seal it first", get_cname());
-  xbt_enforce(gateways_.size() < 2, "NetZone '%s' has more than one gateway, please provide a gateway name", get_cname());
+  xbt_enforce(not gateways_.empty(), "No default gateway has been defined for NetZone '%s'. Try to seal it first",
+              get_cname());
+  xbt_enforce(gateways_.size() < 2, "NetZone '%s' has more than one gateway, please provide a gateway name",
```
Comment (frs69wq) [inline src/kernel/routing/NetZoneImpl.cpp:722]: provide a "unique" gateway name, maybe.

**Review by frs69wq — CHANGES_REQUESTED** [review]
Thanks for this PR, really helpful. I left a few comments along the way.
A few files are only modified because of clang-format, maybe these modifications could be committed outside of the PR.

**Comment by JRodez** [comment]
> Thanks for this PR, really helpful. I left a few comments along the way. A few files are only modified because of clang-format, maybe these modifications could be committed outside of the PR.

Hello, thanks for your comments.

> A few files are only modified because of clang-format, maybe these modifications could be committed outside of the PR.

Which commits are you talking about?

File: src/kernel/routing/NetZoneImpl.cpp [hunk 3]
```diff
@@ -575,58 +466,192 @@ void NetZoneImpl::get_global_route(const NetPoint* src, const NetPoint* dst,
...
+    // ancestor
+    if (src_it + 1 == path_src->end() && dst_it + 1 != path_dst->end()) {
+      *src_ancestor = *src_it;
+      *dst_ancestor = *(dst_it + 1);
+      path_dst->erase(path_dst->begin(), dst_it + 2);
+      break;
+    } else if (dst_it + 1 == path_dst->end() && src_it + 1 != path_src->end()) {
+      *src_ancestor = *(src_it + 1);
+      *dst_ancestor = *dst_it;
+      path_src->erase(path_src->begin(), src_it + 2);
```
[the remark this answers is not in the document]
Comment (JRodez) [reply src/kernel/routing/NetZoneImpl.cpp:520]: Maybe instead of modifying the vectors directly, it would be better to do it a posteriori using 2 index.

**Comment by frs69wq** [comment]
> > A few files are only modified because of clang-format, maybe these modifications could be committed outside of the PR.

> Which commits are you referring to exactly?

I wasn't referring to a specific commit, but I saw some modifications along the way while reviewing the PR that clearly come from clang-format. Not your fault, more likely that of some of us (tipically me ;)) who didn't apply clang-format when committing. Not a big deal, it made it just a tiny bit harder to identify the more important changes. Not critical at all though.

File: src/kernel/routing/NetZoneImpl.cpp (hunk 3 above)
[the remark this answers is not in the document]
Comment (frs69wq) [reply src/kernel/routing/NetZoneImpl.cpp:520]: just explaining in comments what is done here and why can be enough IMHO

File: src/kernel/routing/NetZoneImpl.cpp (hunk 1 above)
Comment (JRodez) [reply src/kernel/routing/NetZoneImpl.cpp:539]: I think this is clear enough now, what do you think ?

**Comment by JRodez** [comment]
I rewrote a large part of the code to make it more understandable.
I have trouble simplifying more.

Note : We should reverse `xxx_path` vectors for using `.erase()` in a more efficient way.

File: src/kernel/routing/NetZoneImpl.cpp (hunk 1 above)
Comment (frs69wq) [reply src/kernel/routing/NetZoneImpl.cpp:539]: Looks good like this

**Review by frs69wq — APPROVED** [review]
Changes look great.

About the note on reversing the paths to optimize the erase operations, I'm not sure it's critical. I'm not expecting to see platforms nesting more than a few zones (10 is already more than what I can imagine).
